name: song-identifier
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.12.31=haa95532_0
  - expat=2.6.4=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.15=h827c3e9_0
  - pip=25.0=py312haa95532_0
  - python=3.12.7=h14ffc60_0
  - setuptools=75.8.0=py312haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.42=haa95532_4
  - vs2015_runtime=14.42.34433=he0abc0d_4
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - audioread==3.0.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - decorator==5.1.1
      - django==1.3
      - filelock==3.17.0
      - fsspec==2025.2.0
      - h5py==3.13.0
      - idna==3.10
      - jinja2==3.1.5
      - joblib==1.4.2
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==2.1.3
      - packaging==24.2
      - pandas==2.2.3
      - platformdirs==4.3.6
      - pooch==1.8.2
      - pycparser==2.22
      - pyside6==6.8.2.1
      - pyside6-addons==6.8.2.1
      - pyside6-essentials==6.8.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - shiboken6==6.8.2.1
      - six==1.17.0
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - torch==2.6.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
prefix: C:\Users\psy-cooper\AppData\Local\miniconda3\envs\song-identifier
